baseURL = 'http://marcelarie.github.io/'
languageCode = 'en-us'
title = 'marcelarie'
theme = "paper-mod"

[params]
defaultTheme = "light"
# defaultTheme: dark
# defaultTheme: auto
[params.homeInfoParams]
Title = "Hi there wave"
Content = "Can be Info, link"
# [params.socialIcons]
# name = "github"
# url  = "https://github.com/marcelarie"
